## Stage 1 : build with maven builder image with native capabilities
FROM quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-21@sha256:e9d2f653444a7383985aa6c0a613d9716cb4a3e99bc8e0171abd7cddbe366592 AS build
COPY --chown=quarkus:quarkus --chmod=0755 mvnw /code/mvnw
COPY --chown=quarkus:quarkus .mvn /code/.mvn
COPY --chown=quarkus:quarkus pom.xml /code/
USER quarkus
WORKDIR /code
RUN ./mvnw -B org.apache.maven.plugins:maven-dependency-plugin:3.8.1:go-offline
COPY src /code/src
ARG QUARKUS_PROFILE=prod
ARG APP_NAME=atm-layer-reporting-service
RUN ./mvnw package -Dnative -Dquarkus.application.name=${APP_NAME} -Dquarkus.profile=${QUARKUS_PROFILE} -DskipTests

## Stage 2 : create the docker final image
FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0@sha256:c0da7af9c09b8537add5f7d4764fcfc37d023e8993ac85ab89af3580b645c2bd
WORKDIR /work/
COPY --from=build /code/target/*-runner /work/application

# set up permissions for user `1001`
RUN chmod 775 /work /work/application \
  && chown -R 1001 /work \
  && chmod -R "g+rwX" /work \
  && chown -R 1001:root /work

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]