CREATE TABLE "PAGOPA_TRANSACTIONS" (
    "ID" BIGINT PRIMARY KEY,
    "TRANSACTION_ID" VARCHAR(36) NOT NULL UNIQUE,
    "STATUS" VARCHAR(1) NOT NULL,
    "BILL_ACCOUNT_ID" VARCHAR(36) NOT NULL,
    "BILL_AMOUNT" NUMERIC NOT NULL,
    "SENDER_BANK" VARCHAR(5) NOT NULL,
    "PAY_DATE" TIMESTAMPTZ NOT NULL,
    "REPORTED" BOOLEAN NOT NULL,
    "BILLER_IBAN" VARCHAR(27) NOT NULL,
    "BILL_ID" VARCHAR(18) NOT NULL,
    "BILLER_COMMISSION" NUMERIC NOT NULL,
    "BANK_COMMISSION" NUMERIC NOT NULL,
    "IDEMPOTENCY_KEY" VARCHAR(22) NOT NULL,
    "BILLER_FISCAL_CODE" VARCHAR(11) NOT NULL,
    "NOTICE_NUMBER" VARCHAR(36) NOT NULL,
    "RET_CODE" VARCHAR(4) NOT NULL,
    "OUTCOME_CODE" VARCHAR(1) NOT NULL,
    "PAY_DESCRIPTION" VARCHAR(210) NOT NULL,
    "BILLER_NAME" VARCHAR(140) NOT NULL,
    "BILLER_OFFICE" VARCHAR(140) NOT NULL,
    "PAY_OPT_AMOUNT" NUMERIC,
    "PAY_OPT_TYPE" VARCHAR(3),
    "PAY_OPT_DUEDATE" TIMESTAMPTZ,
    "PAY_OPT_NOTE" VARCHAR(210),
    "PAY_TOKEN" VARCHAR(35) NOT NULL,
    "TOKEN_EXP_DT" TIMESTAMPTZ NOT NULL,
    "CRD_REFERENCE_ID" VARCHAR(35) NOT NULL,
    "ATM_CODE" VARCHAR(10) NOT NULL
);

CREATE TABLE "PAGOPA_TRANSFER_LIST" (
    "ID" BIGINT PRIMARY KEY,
    "TRANSACTION_ID" BIGINT NOT NULL,
    "TRANSFER_ID" INTEGER NOT NULL,
    "TRANSFER_AMOUNT" NUMERIC NOT NULL,
    "TRANSFER_CRO" VARCHAR(35),
    "FLOW_ID" VARCHAR(35),
    "PAGOPA_REPORTED" BOOLEAN NOT NULL,
    "TRANSFER_EXECUTION_DT" DATE,
    "PA_FISCAL_CODE" VARCHAR(11) NOT NULL,
    "PA_NAME" VARCHAR(140),
    "PA_IBAN" VARCHAR(34) NOT NULL,
    "RMT_INFO" VARCHAR(140) NOT NULL,
    CONSTRAINT "FK_PAGOPA_TRANSFER_LIST_TRANSACTION" FOREIGN KEY ("TRANSACTION_ID") REFERENCES "PAGOPA_TRANSACTIONS"("ID")
);

CREATE TABLE "CBILL_ABI_FEDERAZIONE" (
    "ABI" VARCHAR(5) PRIMARY KEY,
    "PAGOPA_ID" VARCHAR(35) NOT NULL,
    "PSP_FISCAL_CODE" VARCHAR(11) NOT NULL,
    "PSP_CHANNEL" VARCHAR(5) NOT NULL,
    "PAGOPA_DIRECT" BOOLEAN
);

CREATE INDEX "IDX_PAGOPA_TRANSFER_LIST_TRANSACTION" ON "PAGOPA_TRANSFER_LIST" ("TRANSACTION_ID");
